on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/hello
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: body
          assignees: |
            alexrygalov
      - uses: ./.github/actions/docker
        id: hello
        with:
          who-to-greet: "Pew Pew"
      - run: |
          echo "Time: ${{ steps.issue.outputs.issue }}"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
